version: '3.4'

services:
  tasklist:
    image: ${DOCKER_REGISTRY}tasklist
    build:
      context: .
      dockerfile: TaskList/Dockerfile
    depends_on: 
      - tasklist-db
    environment:
      - ConnectionStrings__DefaultConnection=Server=tasklist-db;Database=Tasks;uid=sa;pwd=P@ssw0rd;MultipleActiveResultSets=true

  tasklist-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd